all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: centos
    ansible_become: true
    security_mode: sasl_ssl
preflight:
  hosts:
    ec2-34-222-233-178.us-west-2.compute.amazonaws.com:
    ec2-52-88-17-101.us-west-2.compute.amazonaws.com:
    ec2-54-245-169-77.us-west-2.compute.amazonaws.com:
    ec2-34-223-41-179.us-west-2.compute.amazonaws.com:
    ec2-34-221-68-193.us-west-2.compute.amazonaws.com:
    ec2-34-219-236-49.us-west-2.compute.amazonaws.com:
ssl_CA:
  hosts:
    ec2-34-222-233-178.us-west-2.compute.amazonaws.com:
zookeeper:
  hosts:
    ec2-34-222-233-178.us-west-2.compute.amazonaws.com:
    ec2-52-88-17-101.us-west-2.compute.amazonaws.com:
    ec2-54-245-169-77.us-west-2.compute.amazonaws.com:
    ec2-34-223-41-179.us-west-2.compute.amazonaws.com:
    ec2-34-221-68-193.us-west-2.compute.amazonaws.com:
broker:
  hosts:
    ec2-34-222-233-178.us-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 1
    ec2-52-88-17-101.us-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 2
    ec2-54-245-169-77.us-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 3
    ec2-34-223-41-179.us-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 4
    ec2-34-221-68-193.us-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 5
schema-registry:
  hosts:
    ec2-34-219-236-49.us-west-2.compute.amazonaws.com:
control-center:
  hosts:
    ec2-34-219-236-49.us-west-2.compute.amazonaws.com:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: ec2-34-219-236-49.us-west-2.compute.amazonaws.com:8083
connect-distributed:
  hosts:
    ec2-34-219-236-49.us-west-2.compute.amazonaws.com:
kafka-rest:
  hosts:
    ec2-34-219-236-49.us-west-2.compute.amazonaws.com:
ksql:
  hosts:
    ec2-34-219-236-49.us-west-2.compute.amazonaws.com:
tools:
  hosts:
    ec2-34-219-236-49.us-west-2.compute.amazonaws.com:
